base_model: meta-llama/Meta-Llama-3.1-70B-Instruct
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

# load_in_8bit: true # can't do on h100
# load_in_4bit: true
strict: false

chat_template: llama3
datasets:
  - path: REPLACE__INVALID__INVALID
    type: chat_template
    chat_template: llama3
    field_messages: messages
    message_field_role: role
    message_field_content: content
    roles:
      system:
        - system
      user:
        - user
      assistant:
        - assistant

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out/qlora-llama3-70b-instruct

adapter: lora
lora_model_dir:

sequence_len: 3072
sample_packing: true
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: llama31_70b_finetuning
wandb_entity: YOUR_WANDB_ENTITY_HERE
wandb_watch:
wandb_name:
wandb_log_model:

# step size = gradient_accumulation_steps * micro_batch_size * gpu_count
gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: __INVALID__
optimizer: adamw_torch
lr_scheduler: linear
learning_rate: 2e-4

train_on_inputs: false
# DECIDE: could be faster
# but cause training loss to oscillate (see config)
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true # TODO: probably good to change or something??
early_stopping_patience:
resume_from_checkpoint:
# auto_resume_from_checkpoints: true
local_rank:
logging_steps: 1

xformers_attention:
flash_attention: true
# flash_optimum: true
# flash_attn_fuse_qkv: true
# flash_attn_fuse_mlp: true
# sdp_attention: true

# Liger kernel!
# Kind of experimental but speeds things up
plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_swiglu: true
liger_fused_linear_cross_entropy: true

# Don't use s2_attention (don't need it for 3072)

# empirically, 28 steps for p1 on 4 gpu, so lets just save four times
saves_per_epoch: 2
evals_per_epoch: 2
save_total_limit: 100000

# max_steps: 10

warmup_steps: 1
# evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
eval_sample_packing: false
# saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.01
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: false
  fsdp_sync_module_states: true
  fsdp_offload_params: false
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  # fsdp_activation_checkpointing: true # use instead of vanilla grad checkpoint
  # fsdp_activation_checkpointing_reentrant: true
special_tokens:
  pad_token: <|end_of_text|>
