import logging
from typing import List, Optional
import hydra
import torch
import wandb
import aiofiles
import asyncio
import copy
import os
import numpy as np
import random
from omegaconf import DictConfig, OmegaConf
from pathlib import Path
from transformers import AutoTokenizer
from collections import OrderedDict
import yaml

from ciphers.composecipher import compose_ciphers
from ciphers.encoding import get_cipher_from_params, parse_cipher_name
from ciphers.type import AbstractCipher
from .data_loading_with_cipher import get_harmful_datasets, load_and_preprocess_data
from .feature_extraction import extract_features, ensure_cached_features
from .train_probes import train_and_evaluate_probes
from .evaluation import evaluate_probes, probe_output_location
from .utils import set_seed
from ciphers import get_cipher
from old_harness.utility import find_project_root
from .measure_time import measure_time
import multiprocessing
from functools import partial

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

phase = "phase_ii"

async def detect_valid_ciphers(pipeline_outputs_dir: Path, accuracy_threshold: float = 0.5):
    """
    Detect valid ciphers from phase 2 evaluation caches.
    Returns a dictionary mapping cipher names to cipher parameters.
    """
    valid_ciphers = {}
    eval_cache_files = list(pipeline_outputs_dir.glob(f"**/{phase}/harmful_eval_cache.txt"))

    async def process_eval_cache(eval_cache):
        try:
            async with aiofiles.open(eval_cache, "r") as f:
                content = await f.read()
            accuracy = float(content.strip())
            if accuracy > accuracy_threshold or phase == "phase_ii":
                # Get the cipher directory (parent of 'phase_ii')
                cipher_dir = eval_cache.parent.parent
                # Get the relative path of cipher_dir from pipeline_outputs_dir
                cipher_rel_path = cipher_dir.relative_to(pipeline_outputs_dir)
                # Use the relative path as cipher name to include subdirectory structure
                cipher_name = str(cipher_rel_path)
                cipher_class_name, cipher_params = parse_cipher_name(cipher_rel_path)
                valid_ciphers[cipher_name] = {
                    "class_name": cipher_class_name,
                    "params": cipher_params,
                    "path": cipher_dir
                }
                log.info(f"Cipher {cipher_name} is valid with accuracy {accuracy:.2f}.")
            else:
                log.info(f"Cipher {eval_cache.parent.parent.name} has accuracy {accuracy:.2f}, below threshold.")
        except Exception as e:
            log.warning(f"Failed to process {eval_cache}: {e}")

    await asyncio.gather(*[process_eval_cache(eval_cache) for eval_cache in eval_cache_files])

    # Add plaintext cipher (no LoRA applied)
    valid_ciphers['plaintext'] = {
        "class_name": "IdentityCipher",
        "params": {},
        "path": None  # No path since no LoRA model
    }
    return valid_ciphers


async def process_cipher_data(cipher_name, cipher_info, tokenizer, model, model_load_distributed, model_quantization, benign_dataset, jailbreak_dataset, num_samples, cipher_cache_dir, device, wrapping_ciphers: List[AbstractCipher] = []):
    """
    (Autogenerated docstring)
    Process data for a specific cipher, including encryption, tokenization, and feature extraction.

    Args:
        cipher_name (str): Name of the cipher being processed.
        cipher_info (dict): Information about the cipher, including class name and parameters.
        tokenizer: The tokenizer to use for processing text.
        model (str): The name or path of the base model.
        model_load_distributed (bool): Whether to load the model in a distributed manner.
        model_quantization (str): The quantization method to use for the model, if any.
        benign_dataset (str): Path or name of the benign dataset.
        jailbreak_dataset (str): Path or name of the jailbreak dataset.
        num_samples (int): Number of samples to process from each dataset.
        cipher_cache_dir (str): Directory to use for caching cipher-related data.
        device (torch.device): The device to use for computations.
        wrapping_cipher (Optional[AbstractCipher]): An optional cipher to apply over the cipher used during fine-tuning.

    Returns:
        tuple: A tuple containing:
            - features (dict): Extracted features for each layer.
            - labels (list): Labels for the processed data.
            - prompts (list): Original text prompts.

    This function performs the following steps:
    1. Initializes the cipher based on the provided information.
    2. Prepares the data by loading and preprocessing it.
    3. Extracts features from the processed data using the specified model.

    The function uses caching to improve performance for repeated runs with the same data.
    """

    cipher_name_in_info = cipher_info["class_name"]
    cipher_params = cipher_info["params"]
    cipher_out_path = cipher_info.get("path")
    lora_path = None
    if cipher_out_path:
        lora_path = cipher_out_path / phase
    
    if cipher_out_path and (cipher_out_path / "cipher_params.json").exists():
        import json
        with open(cipher_out_path / "cipher_params.json", "r") as f:
            cipher_params = json.load(f)
            cipher = await get_cipher_from_params(cipher_params)
    else:
        # Hacky manual inverse map for now
        cipher_name_to_class_name = {
            "EndSpeak": "EndSpeakCipher",
        }

        cipher_class_name = cipher_name_to_class_name.get(cipher_name_in_info, cipher_name_in_info)

        # Initialize the cipher
        cipher = await get_cipher(cipher_class_name, **cipher_params)
        log.info(f"Using cipher: {cipher_class_name} with params: {cipher_params}")


    if not wrapping_ciphers:
        wrapping_ciphers = ['plaintext']

    # Prepare data

    if lora_path:
        # assert False, "LORA path is not supported yet"
        fine_tuned_model_path = str(lora_path)  # Set the fine-tuned model
    else:
        # fine_tuned_model_path = "/workspace/ft-robustness/ft_robustness/benign_ft/outputs/out/oasst2-llama3-70b-instruct"
        fine_tuned_model_path = None  # Use base model for plaintext

    defaultciphercache = find_project_root() / 'cipher_cache'
    cache_dir = Path(cipher_cache_dir or defaultciphercache)

    prompts = []
    tokenized_prompts = []
    labels_all = []
    prompts_plaintext = []
    generating_ciphers = []
    for wrapping_cipher in wrapping_ciphers:
        if wrapping_cipher != 'plaintext':
            wrapping_cipher = await get_cipher(wrapping_cipher)
            newcipher = compose_ciphers(cipher, wrapping_cipher)
            newciphername = f"{cipher_name}-{wrapping_cipher.name()}"
        else:
            newcipher = cipher
            newciphername = cipher_name
        # Optionally, append cipher_name to cache_dir to separate caches per cipher
        cache_dir = cache_dir / newciphername.replace('/', '_')

        # Load and preprocess data without cfg
        data = await load_and_preprocess_data(
            benign_dataset=benign_dataset,
            jailbreak_dataset=jailbreak_dataset,
            num_samples=num_samples,
            tokenizer=tokenizer,
            cipher=newcipher,
            cipher_params=cipher_params,
            cache_dir=cache_dir
        )
        # Extract data components
        # prompts = data.text_prompts
        # tokenized_prompts = data.prompts
        # labels = data.labels
        prompts.extend(data.text_prompts)
        prompts_plaintext.extend(data.plaintext_prompts)
        tokenized_prompts.extend(data.prompts)
        labels_all.append(data.labels)
        generating_ciphers.extend([newciphername] * len(data.text_prompts))

    labels = np.concatenate(labels_all, axis=0)

    # Extract features
    # Create cfg_copy with necessary fields for extract_features
    cfg_copy = DictConfig({
        'model': model,
        'fine_tuned_model': fine_tuned_model_path,
        'model_load_distributed': model_load_distributed,
        'model_quantization': model_quantization,
    })

    features = await ensure_cached_features(cfg_copy, tokenized_prompts, device, prompts_text=prompts, prompts_plaintext=prompts_plaintext, cipher_name=generating_ciphers, jailbreak_dataset=jailbreak_dataset, plaintext_dataset=benign_dataset)

    return features, labels, prompts

def process_cipher_data_sync(args):
    return asyncio.run(process_cipher_data(*args))

@measure_time
async def collect_data_and_features(ciphers_dict, tokenizer, model, model_load_distributed, model_quantization, benign_dataset, jailbreak_dataset, num_samples, cipher_cache_dir, parallel_data_collection, device, in_context_ciphers):
    """
    Collects data and features from multiple ciphers, maintaining separate cipher dimensions.
    """

    if parallel_data_collection:
        with multiprocessing.Pool(processes=60) as pool:
            args_list = [(cipher_name, cipher_info, tokenizer, model, model_load_distributed, model_quantization, benign_dataset, jailbreak_dataset, num_samples, cipher_cache_dir, device, in_context_ciphers) for cipher_name, cipher_info in ciphers_dict.items()]
            results = pool.map(process_cipher_data_sync, args_list)
    else:
        tasks = [process_cipher_data(cipher_name, cipher_info, tokenizer, model, model_load_distributed, model_quantization, benign_dataset, jailbreak_dataset, num_samples, cipher_cache_dir, device, in_context_ciphers) for cipher_name, cipher_info in ciphers_dict.items()]
        results = await asyncio.gather(*tasks)

async def run_experiment(cfg: DictConfig):
    log.info(OmegaConf.to_yaml(cfg))
    
    if not cfg.eval_only:
        # Save the configuration YAML file
        output_dir = probe_output_location(cfg)
        output_dir.mkdir(parents=True, exist_ok=True)
        config_yaml_path = output_dir / "experiment_config.yaml"
        
        with open(config_yaml_path, 'w') as f:
            yaml.dump(OmegaConf.to_container(cfg, resolve=True), f)
        
        log.info(f"Saved experiment configuration to {config_yaml_path}")

    seed = cfg.get('seed', 42)
    set_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    pipeline_outputs_dir = Path(cfg.pipeline_outputs_dir)
    all_valid_ciphers = await detect_valid_ciphers(pipeline_outputs_dir, accuracy_threshold=cfg.accuracy_threshold)
    log.info(f"Detected valid ciphers: {list(all_valid_ciphers.keys())}")
    assert all_valid_ciphers is not None and len(all_valid_ciphers) > 0, "No valid ciphers found"

    tokenizer = AutoTokenizer.from_pretrained(cfg.model)

    await collect_data_and_features(
        all_valid_ciphers, tokenizer, cfg.model, 
        cfg.get('model_load_distributed', False), cfg.get('model_quantization', None),
        # We don't care about the benign dataset for CMFT
        None, # "hf://tatsu-lab/alpaca",
        get_harmful_datasets(),
        1024, 
        cfg.get('cipher_cache_dir'), cfg.get('parallel_data_collection', False), device,
        cfg.get('in_context_ciphers', [])
    )    

if __name__ == "__main__":
    from .configurations import base
    asyncio.run(run_experiment(base))
